#Gradle
org.gradle.jvmargs=-Xmx8g -Dfile.encoding=UTF-8 -XX:+UseParallelGC
org.gradle.parallel=true
org.gradle.daemon=true

org.gradle.toolchains.jvm.version=21

#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx6G

#Android
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.incremental.jvm.fir=true

android.uniquePackageNames=false
android.dependency.useConstraints=false

android.newDsl=true
android.builtInKotlin=true

#MPP
kotlin.mpp.enableCInteropCommonization=true
kotlin.mpp.stability.nowarn=true
kotlin.mpp.androidSourceSetLayoutVersion=2
kotlin.apple.xcodeCompatibility.nowarn=true

#KiteTorrent
group=io.github.yuroyami
version=0.0.1
